AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda
  Sample SAM Template for lambda

Params:
  CHANNEL_ACCESS_TOKEN:
    type: String
  CHANNEL_SECRET:
    type: String
  PORT:
    type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LineBotCommonPythonLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Layer of Python Common Logic
      CompatibleRuntimes:
        - python3.8
      ContentUri: ../layer/python
    Metadata:
      BuildMethod: python3.8

  LineBotCommonBinaryLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Layer of Chrome Binary
      CompatibleRuntimes:
        - provided.al2
      ContentUri: ../layer
    Metadata:
      BuildMethod: makefile

  ReservatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          CHANNEL_ACCESS_TOKEN: !Ref CHANNEL_ACCESS_TOKEN
          CHANNEL_SECRET: !Ref CHANNEL_SECRET
          PORT: !Ref PORT
      CodeUri: linebot_handler/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
      Layers:
        - !Ref LineBotCommonPythonLibLayer
        - !Ref LineBotCommonBinaryLayer

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LineBotReservatorApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ReservatorFunction:
    Description: "LineBot Reservator Lambda Function ARN"
    Value: !GetAtt ReservatorFunction.Arn
  ReservatorFunctionIamRole:
    Description: "Implicit IAM Role created for LineBot Reservator Function"
    Value: !GetAtt ReservatorFunctionRole.Arn
