name: Mirroring
on:
  push:
    branches:
      - master
env:
  CODECOMMIT_SSH_KEY_ID: ${{secrets.CODECOMMIT_SSH_KEY_ID}}
  CODECOMMIT_SSH_PRIVATE_KEY: ${{secrets.CODECOMMIT_SSH_PRIVATE_KEY}}
  CODECOMMIT_REPO_SSH_URL: ${{secrets.CODECOMMIT_REPO_SSH_URL}}
  CODECOMMIT_SSH_CONFIG: ${{secrets.CODECOMMIT_SSH_CONFIG}}

jobs:
  to_codecommit:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{env.CODECOMMIT_REPO_SSH_URL}}
          ssh_private_key:
            ${{env.CODECOMMIT_SSH_PRIVATE_KEY}}
          ssh_username:
            ${{env.CODECOMMIT_SSH_KEY_ID}}
      # - name: push to aws codecommit
      #   shell: bash
      #   run: |
      #     mkdir ~/.ssh
      #     echo "$CODECOMMIT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      #     echo "$CODECOMMIT_SSH_CONFIG" > ~/.ssh/config && chmod 600 ~/.ssh/config
      #     ssh-keyscan "$CODECOMMIT_HOST" >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
      #     git remote add codecommit "$CODECOMMIT_REPO_URL"
      #     git config --get remote.codecommit.url
      #     git push codecommit master:main