name: Mirroring
on:
  push:
    branches:
      - master
env:
  CODECOMMIT_SSH_KEY_ID: ${{secrets.CODECOMMIT_SSH_KEY_ID}}
  CODECOMMIT_SSH_PRIVATE_KEY: ${{secrets.CODECOMMIT_SSH_PRIVATE_KEY}}
  CODECOMMIT_REPO_SSH_URL: ${{secrets.CODECOMMIT_REPO_SSH_URL}}

jobs:
  to_codecommit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            $CODECOMMIT_REPO_SSH_URL
          ssh_private_key:
            $CODECOMMIT_SSH_PRIVATE_KEY
          ssh_username:
            $CODECOMMIT_SSH_KEY_ID